#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MISC_2 21

//Moving >10
#define OBJECT_TYPE_MARIO		10
#define OBJECT_TYPE_GOOMBA		11
#define OBJECT_TYPE_PARAGOOMBA	12
#define OBJECT_TYPE_KOOPA		13
#define OBJECT_TYPE_PARAKOOPA	14
#define OBJECT_TYPE_FIREPLANT	15
#define OBJECT_TYPE_BULLETFIRE	16
#define OBJECT_TYPE_BITEPLANT	17

//Disappear-able >20
#define OBJECT_TYPE_COIN 20
#define OBJECT_TYPE_MUSHROOM 21
#define OBJECT_TYPE_LEAF 22
#define OBJECT_TYPE_STAR 23
#define OBJECT_TYPE_HIDEDCOIN 24

//Stable >30
#define OBJECT_TYPE_INVISIBLE_BLOCK	30
#define OBJECT_TYPE_DIRT_BRICK	31
#define OBJECT_TYPE_GLASS_BRICK	32
#define OBJECT_TYPE_QUEST_BRICK_LEVELUP	33
#define OBJECT_TYPE_QUEST_BRICK_COIN	34

//Platform >40
#define OBJECT_TYPE_PLATFORM 40
#define OBJECT_TYPE_DIRT 41
#define OBJECT_TYPE_CLOUD 42

#define OBJECT_TYPE_COLOR_BOX 43
#define OBJECT_TYPE_GREEN_PIPE 44
#define OBJECT_TYPE_BIG_DIRT 45

//Others >50
#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_TREES 51
#define OBJECT_TYPE_BUSH 52
#define OBJECT_TYPE_CLOUD1 53
#define OBJECT_TYPE_CLOUD2 54
#define OBJECT_TYPE_CLOUD3 55
#define OBJECT_TYPE_BLACK_END 56

#pragma region Moving Obj
#pragma region MARIO 

#define ID_SPRITE_MARIO (OBJECT_TYPE_MARIO * 10000)
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_GOOMBA (OBJECT_TYPE_GOOMBA*10000)
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#pragma endregion 


#pragma region Disappear-able
#define ID_SPRITE_COIN (OBJECT_TYPE_COIN*10000)
#pragma endregion


#pragma region Stable
#define ID_SPRITE_BRICK (OBJECT_TYPE_INVISIBLE_BLOCK*10000)
#define ID_SPRITE_DIRT_BRICK (OBJECT_TYPE_DIRT_BRICK*1000)

#define ID_SPRITE_GLASS_BRICK (OBJECT_TYPE_GLASS_BRICK*1000)
#define ID_SPRITE_QUEST_BRICK (OBJECT_TYPE_QUEST_BRICK*1000)
#pragma endregion

#pragma region Platform
#define ID_SPRITE_DIRT (OBJECT_TYPE_DIRT*10000)
#define ID_SPRITE_DIRT_BEGIN (ID_SPRITE_DIRT+1000)
#define ID_SPRITE_DIRT_MIDDLE (ID_SPRITE_DIRT+2000)
#define ID_SPRITE_DIRT_END (ID_SPRITE_DIRT+3000)

#define ID_SPRITE_CLOUD (OBJECT_TYPE_CLOUD*10000)
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPRITE_COLOR_BOX (OBJECT_TYPE_COLOR_BOX*10000)
#define ID_SPRITE_GREEN_PIPE (OBJECT_TYPE_GREEN_PIPE*10000)
#define ID_SPRITE_BIG_DIRT (OBJECT_TYPE_BIG_DIRT*10000)
#pragma endregion

//Others...